name: make

on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install -y graphviz
    - name: build
      run: make