name: make

on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install -y graphviz ghostscript
    - name: build
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: output
        path: |
          diagram-light.png
          diagram-light-thumbnail.png
          diagram.ps.gz
          diagram-thumbnail.png
          diagram.png
          diagram.dot
          concepts-history.html
          diagram-light.pdf
          diagram-light.ps.gz
          syntax-across-languages.html
          diagram.pdf
          diagram-light.dot